version: '3.8'

services:
  consul:
    image: hashicorp/consul:1.15
    container_name: consul-server
    restart: always
    volumes:
     - ./service_a.hcl:/etc/consul.d/service_a.hcl
     - ./service_b.hcl:/etc/consul.d/service_b.hcl
     - ./consul.hcl:/etc/consul.d/consul.hcl
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -server -bootstrap -ui -client=0.0.0.0 -config-dir=/etc/consul.d"
    networks:
      - app-network

  service_a:
    build:
      context: .
      dockerfile: dockerfile.service_a
    container_name: service_a
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - consul

  service_a_proxy:
    image: hashicorp/consul:1.15
    command: "connect proxy -sidecar-for service_a"
    network_mode: "service:service_a"
    depends_on:
      - consul
      - service_a
    

  service_b:
  
    build:
      context: .
      dockerfile: dockerfile.service_b
    container_name: service_b
    ports:
      - "5001:5001"
    environment:
      - SERVICE_A_URL=http://localhost:8080/data
    networks:
      - app-network
    depends_on:
      - consul
      - service_a

  service_b_proxy:
    image: hashicorp/consul:1.15
    command: "connect proxy -sidecar-for service_b -upstream service_a:8080"
    network_mode: "service:service_b"
    depends_on:
      - consul
      - service_b
   
networks:
  app-network:
    driver: bridge
