version: '3.8'

services:
  consul:
    image: hashicorp/consul:1.15
    container_name: consul-server
    restart: always
    volumes:
      - ./consul.hcl:/consul/config/consul.hcl
      - ./service_a.hcl:/consul/config/service_a.hcl
      - ./certs:/consul/certs
    ports:
      - "8501:8501"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -config-file=/consul/config/consul.hcl"
    networks:
      - app-network

  service_a:
    build:
      context: .
      dockerfile: dockerfile.service_a
    container_name: service_a
    ports:
      - "5000:5000"
    environment:
      - CONSUL_HTTP_ADDR=https://consul:8501
    volumes:
      - ./certs:/certs
    networks:
      - app-network
    depends_on:
      - consul
    

  service_b:

    build:
      context: .
      dockerfile: dockerfile.service_b
    container_name: service_b
    ports:
      - "5001:5001"
    environment:
      - CONSUL_HTTP_ADDR=https://consul:8501
    volumes:
      - ./certs:/certs
    networks:
      - app-network
    depends_on:
      - consul
      - service_a
   
networks:
  app-network:
    driver: bridge
